version: "3"
services:
  node:
    image: node:18-bullseye
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    ports:
      - 3000:3000
    command: "bash -c 'npm install && npm run dev'"
